const DATABASE_NAME = '@gameplay';

const COLLECTION_USER = `${DATABASE_NAME}:users`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLECTION_USER,
    COLLECTION_APPOINTMENTS
};